# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='waiting_status',
            new_name='dep_location',
        ),
    ]
