# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
